name: smart_dev_widgets
description: A collection of reusable Flutter widgets for common UI components by SmartDev.
version: 0.0.3
homepage: https://github.com/developerdivyaraj/smart-dev-widgets
repository: https://github.com/developerdivyaraj/smart-dev-widgets

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/